repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.5
  hooks:
    - id: ruff
      types_or: [ python, pyi ]
      args: [--fix, --show-fixes, --exit-non-zero-on-fix]

    - id: ruff-format
      types_or: [ python, pyi ]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        additional_dependencies: [
          "instaloader>=4.14.1",
          "pillow>=11.1.0",
          "tqdm>=4.67.1",
          "mypy>=1.15.0",
          "pre-commit>=4.2.0",
          "pylint>=3.3.6",
          "ruff>=0.11.5",
          "types-pillow>=10.2.0.20240822",
          "types-tqdm>=4.67.0.20241221"
        ]
        args: [--strict]
